### ISSUE TITLE
Improve Mishka shell to recognize started-service different way

### ISSUE THREAD

**Issue by shahryarjb** [shahryarjb/mishka-cms#191]
Hi, when a user start a server with `Mishka` shell and delete the source of code or the directory, after that if he/she clone the source again and start the server, they are going to get error.

```
another apps using port 80 or 443, please kill the apps and rerun mishka.sh !
```
So we need to  recognize started-service different way to let user start shell and access to our options

**Comment by mojtaba-naseri** [comment]
fix this issue by this commit https://github.com/mojtaba-naseri/mishka-cms/commit/9226eda9eb1dac80994a8a99ca83dc4e9ab74e85
