### ISSUE TITLE
Make mishka shell's selections compatible with number of options

### ISSUE THREAD

**Issue by shahryarjb** [shahryarjb/mishka-cms#192]
Hi, Mishka `shell` ask some questions like “what web server do you need?” or what env you think is better for you!! After seeing this we should write full word, it can make user confuse, hence if the shell accept number and word together the problem is fixed.

**Comment by mojtaba-naseri** [comment]
fix this by commit https://github.com/mojtaba-naseri/mishka-cms/commit/e2132107e76bd2306bd79f9463cbf32a004c7800
